### ISSUE TITLE
Erro na conexão c/ webservice

### ISSUE THREAD

**Issue by joao-digitalmkt** [willstorm/correios#33]
O módulo começou a apresentar o seguinte erro na loja: "System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: http://ws.correios.com.br/CalcPrecoPrazo. at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest() at System.Web.Services.Protocols.SoapServerProtocol.Initialize() at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)".

Alguém saberia resolver isso?

**Comment by willstorm** [comment]
Por favor, veja a correção em https://github.com/willstorm/correios/issues/32

**Comment by joao-digitalmkt** [comment]
Obrigado! Vou alterar.

Só aproveitando o tópico, gostaria de perguntar o seguinte: se eu criar um status "Pedido entregue", associar esse status ao estado "complete" e ativar esse status quando a remessa for dada como entregue nos correios? Vc já pensou em implementar algo do tipo?
