### ISSUE TITLE
Cálculo no carrinho não aparece

### ISSUE THREAD

**Issue by geraldopacheco** [willstorm/correios#4]
Bom dia! Estou usando o magento 1.8 e o módulo parece estar instalado e configurado corretamente, desativei todos os demais e deixei só este habilitado. Quando entra no carrinho de compra a tela de simulação de frete aparece com o campo "estado", apesar de eu ter configurado para não aparecer e quando digito estado e CEP, não funciona. O curioso é que avançando para o checkout ele mostra as duas opções (PAC e SEDEX) corretamente. 

Endereço: www.segredoerotico.com.br/repair/

Configurei o 2º produto em destaque (INA) com dimensões e pesos corretos para teste.

Obrigado!

**Comment by barret0** [comment]
Obrigado maxgdias, funcionou aqui
