### ISSUE TITLE
Cod. Serviço 05/05/2017

### ISSUE THREAD

**Issue by valiati100** [willstorm/correios#45]
Parece que o correio atualizou o cod. de serviço para pac e sedex.

Pac: Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04510.
Sedex: Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04014.

**Comment by mathcale** [comment]
@valiati100 Pelo que reparamos aqui, esses códigos são para os métodos "Sem Contrato". Para corrigir isso, siga esses passos:

1. Abra o arquivo `Methods.php`, localizado em `app/code/community/Storm/Correios/Model/Source`;
2. No array com label "Without Contract", troque os valores das chave `value`s pelo que está sendo informado na mensagem de erro (no nosso caso, o do PAC fica 04510 e do SEDEX, 04014);
3. Vá na administração do Magento -> Configurações -> Sistema -> Formas de Entrega -> Correios -> Selecione o PAC e o SEDEX novamente e clique em "Salvar".

Daqui a pouco vou abrir uma PR com a correção. Aí é só esperar o @willstorm aprovar ;)

[]'s

**Comment by valiati100** [comment]
Opa, deu certo. Obrigado :)
Pelo e-mails que recebi dos correios, os códigos com contrato também vão mudar

'Para clientes com contrato, também estão disponíveis novos códigos: PAC 04669 e Sedex 04162.
Mas estes entraram como novos serviços na lista de configuração pois não estão liberados para todos os clientes que possuem contrato.'

**Comment by mathcale** [comment]
Show de bola! Já que deu tudo certo, não se esqueça de fechar esta issue pra não ficar muita coisa acumulada lá na frente e as pessoas com o mesmo problema possam vir direto para a resposta.

**Comment by willstorm** [comment]
Pessoal, obrigado por reportarem o erro. Já fiz a atualização na branch master com as modificações.
